services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - .:/app/
    env_file:
        - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: example-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: