# Generated by Django 5.1 on 2024-08-31 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()], verbose_name='Длинный url'),
        ),
    ]
